src/app/dashboard/[id]/edit/page.tsx
src/app/dashboard/[id]/page.tsx
src/app/dashboard/page.tsx
src/app/page.tsx

Added dynamic edit page. Also fixed the nav a little bit.

feat: add edit recipe page

---

.gitignore
package-lock.json
package.json
prisma/schema.prisma
src/app/db-test/page.tsx
src/lib/db.ts
src/lib/queries.ts

* Add a local sqlite database by adding a `.env` file in the project root, containing `DATABASE_URL="file:./dev.db"`
* See https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices for reference on PrismaClient (`src/lib/db.ts`)
* Run `npx prisma generate` to generate a Prisma client - [see this image](https://www.prisma.io/docs/assets/images/prisma-client-install-and-generate-ece3e0733edc615e416d6d654c05e980.png)

db: add prisma orm to the project

---

.eslintrc.json
.gitignore
src/app/actions/scraper.ts
src/lib/functions.ts
src/lib/recipe.d.ts

added file for global types for recipe

add global types for recipe

---

src/app/layout.tsx
src/app/login/page.tsx
src/app/signup/page.tsx

- Add greybox structure for login in page
- Add greybox structure for sign up page
fixes #10 #11

feat: greybox structure of login page/sign up page

---

prisma/schema.prisma

update .env with connection string from supabase

db: change from sqlite to postgresql (supabase)

---

package-lock.json
package.json
prisma/migrations/20241021111356_init/migration.sql
src/app/db-test/page.tsx
src/app/layout.tsx
src/app/page.tsx

feat: Install mantine and add provider

---

prisma/schema.prisma
src/app/layout.tsx
src/app/test-page/page.tsx
src/lib/auth.ts

This PR introduces a revised version of the login functionality. While it is still used on the 'test-page,' it should be ready to be implemented on the actual login page.
* **auth.ts:** This file contains the authOptions, which specify:
- The session strategy and duration.
- Authentication providers to use (credentials, in this case). It also handles authorization against the database and returns either a user object or null.
- Callback functions for JWT and session management. These callbacks enable storing more than just the default session data (such as email, session expiration date); they also store the user ID, which is essential after the user has logged in.
* **test-page:** The code has been cleaned up. Unnecessary parts + commented-out code have been removed. The remaining code …

feat: improve-login-logic

---

src/app/signup/page.tsx
src/middleware.ts

- /login and /signup now work as they should.
- Changed the link href on the login button on ``/signup`` since it linked to the wrong address.

fix: fixed infinite redirect

---

src/middleware.ts

- Removed redundant if statement
- Declared pathname variable earlier

fix: simplified code for middleware

---

package-lock.json
package.json
src/lib/queries.ts
src/lib/scraper.ts
src/lib/types.d.ts
src/lib/utils.ts

This PR updates getScrapedRecipe to also return the recipe title.
- getScrapedRecipe is updated to use a more dynamic return type, "GetScrapedRecipeResponse".
- Helper functions are edited and a dev dependency is added.
Next steps:
- Update the frontend to make use of the title data.
- Update the saveRecipe function to make use of the title data.

scraper: scrape recipe title

---

src/app/welcome/page.tsx
src/middleware.ts

- If not logged in; homepage is ``/``, if logged in user gets redirected to ``/welcome``.
- Removed conditional rendering based on authentication on ``/welcome``

feat: added authentication based home page

---

package-lock.json
package.json
src/app/api/signup/route.ts
src/app/login/page.tsx
src/app/signup/page.tsx
src/components/SignUpForm.tsx

This PR introduces a sign-up feature. While it is still in its early stages and requires further work, here’s what it accomplishes so far:
Todo:

db: user registration logic

---

package-lock.json
postcss.config.js
src/app/dashboard/page.tsx
src/app/welcome/layout.tsx
src/app/welcome/page.tsx
src/components/RecentRecipes.tsx
src/components/RecipeForm.tsx
src/lib/scraper.ts
src/lib/types.d.ts

- Deleted the unused postcss.config.js file.
- Updated the types.d.ts file to include the userRecipe type

refactor: Remove unused postcss configuration file and update types

---

src/app/dashboard/[id]/edit/page.tsx
src/app/welcome/page.tsx
src/components/CategoryFilter.tsx
src/components/EditRecipeForm.tsx
src/components/Header/Navbar.tsx
src/components/RecipeForm.tsx
src/components/SaveRecipeComponent.tsx
src/lib/queries.ts

- Complete all greybox pages and components

83 feat complete greybox

---

package-lock.json
src/app/dashboard/page.tsx
src/components/RecentRecipes.tsx
src/lib/actions.ts
src/lib/next.auth.d.ts
src/lib/queries.ts

Additions:
- in queries.ts: ``getUserRecipeById`` fetches recipes based on provided userId.
- in actions.ts: ``getUserRecipe`` takes the user id from session and puts it into the function above.
- The ``RecentRecipes``component uses ``getUserRecipe`` and prints the logged in user's recipe.
Note: The functions are very basic and can be rewritten. Will add this to a new issue!

feat: RecentRecipes component shows only user's recipes

---

package.json

I don't know yet if this will work, but it might install playwright on the server...

Add script to install playwright on server

---

src/app/login/page.tsx
src/app/signup/page.tsx
src/app/theme.ts
src/components/EditRecipeForm.tsx
src/components/Header/Navbar.module.css
src/components/Header/Navbar.tsx
src/components/IngredientsAndInstructionsToggle.tsx
src/components/LoginForm.tsx
src/components/RecentRecipes.tsx
src/components/RecipeForm.tsx
src/components/SaveRecipeComponent.tsx
src/components/SignUpForm.tsx

Also add next/link to all Anchors fixing #86 
Fixes #103

feat: remove styling from buttons and add to theme instead

---

src/lib/scraper.ts
src/lib/types.d.ts
src/lib/utils.ts

This PR adds more scraped info: author, total cook time and yield (servings)
- **Author:** the author's name is scraped as a string.
- **Total time:** Time is formatted as "PT3M" (ISO 8601 duration). This is converted using the ``convertTime`` function in utils.ts.
- **Yield:** This is typically represented as a string or number. Occasionally, when it’s a string, it may contain the text "undefined" for unclear reasons. When checking for yield values, "undefined" is removed if present. If the yield is a number, it is converted to a string.

scraper: scrape author, time and yield

---

src/app/dashboard/[id]/edit/loading.tsx
src/app/dashboard/[id]/loading.tsx
src/app/dashboard/[id]/page.tsx
src/app/dashboard/loading.tsx
src/components/DefaultLoadingSpinner.tsx
src/components/RecipeForm.tsx

Some simple loading spinners for the MVP.

feat: create default loading

---

src/components/EditRecipeForm.tsx
src/lib/queries.ts
src/lib/scraper.ts

feat: added new recipe fields to update form

---

src/components/Header/Navbar.module.css
src/components/Header/Navbar.tsx
src/components/IngredientsAndInstructionsToggle.tsx
src/components/RecentRecipes.tsx
src/components/RecipeForm.tsx
src/components/SaveRecipeComponent.tsx

- add container with links on menu open
- only show recent recipes if there are any in `RecentRecipies.tsx`
fixes #91

feat: finish the hamburger menu

---

src/lib/utils.ts

Function now also handles if format includes year, month and day since this sometimes happens (for example P0Y0M0DT0H75M0S).

feat: improve time converter

---

package-lock.json
package.json
src/components/EditRecipeForm.tsx
src/lib/types.d.ts

Refactor EditRecipeForm.tsx 
- `addIngredient` and `addInstruction` into `addItem`.
- Switch view buttons simplified by mapping over view names.
- Validation added to check that the title is filled before submitting.
Add a bottom bar container to save/cancel buttons, just a suggestion, needs more styling
Install lint-staged
Update UserRecipe type to include tags as string[]

feat: Refactor editRecipeComponent

---

src/components/SaveRecipeComponent.tsx

- Put the save feedback (success or error) in modal instead of alerts

feat: replace alerts when recipe is saved

---

src/app/api/signup/route.ts
src/components/LoginForm.tsx
src/components/SignUpForm.tsx

feat: make email lowercase in signup and login forms

---

src/components/CTABanner.tsx
src/components/RecipeForm.tsx

- Don't show CTA if user is logged in

fix: CTA banner should not be shown if user is logged in

---

src/components/EditRecipeForm.tsx

- Make width full, use `<Paper>` element with same styling as navbar and CTA for cohesive look.

feat: update save buttons container in editRecipeForm

---

src/app/theme.ts
src/components/IngredientsAndInstructionsToggle.tsx

- Remove the custom font sizes and use default instead, fixes the issue and suits the site

fix: title causes overflow on x-axis

---

package-lock.json
package.json
src/app/layout.tsx
src/components/CTABanner.tsx
src/components/RecipeForm.tsx
src/lib/scraper.ts
src/lib/utils.ts

This PR updates the error handling in the `getScrapedRecipe` function and in the `RecipeForm` component.
- With this change "unfiltered" errors should hopefully not end up in the frontend.
- Add error message for empty strings
- Add util function `isValidUrl(urlToCheck: string): boolean` and associated error message
- Add custom error message to handle common error returned by `await page.goto(url)` (original message is not formatted for UI)
- Mantine Notification system is introduced as an error handling solution for the frontend that also handles loading state and success message.

fix: error message handling in RecipeForm

---

src/components/LoginForm.tsx
src/components/RecipeForm.tsx
src/components/SignUpForm.tsx

refactor the error handling to use the Mantine notification system.

feat: update error handling on signup and login forms

---

src/components/Header/Navbar.tsx

Refactored the burger menu to be a drawer with both X button and click outside to close. Could be built differently but this fixes the issue.

fix: close navbar when clicking the X

---

prisma/migrations/20241113123502_add_created_at_and_updated_at/migration.sql
prisma/schema.prisma
src/lib/queries.ts
src/lib/types/types.d.ts

add createdAt and updatedAt fields to Recipe model

---

prisma/migrations/20241113123502_add_created_at_and_updated_at/migration.sql
prisma/schema.prisma
src/app/dashboard/page.tsx
src/app/welcome/page.tsx
src/components/RecipesList.tsx
src/components/SaveRecipeModal.tsx
src/lib/actions.ts
src/lib/queries.ts
src/lib/types/types.d.ts

Implement Recent Recipes list.
- Update schema and migrations
- Update getRecipesByUserId to take parameters for what to order by, if order should be desc/asc and a number for limit of results.
- Change component name from RecentRecipes -> RecipesList and update its title to be passed as props 
- Implement RecipesList in "/dashboard" and "/welcome"
- Update RecipesList with latest saved recipe using router.refresh()

feat: implement recent recipes list

---

src/app/dashboard/[slug]/page.tsx
src/components/RecipeForm.tsx
src/components/RenderedInstructions.tsx
src/components/ScreenAwakeToggle.tsx

- Add checkboxes to instructions, when checked change opacity to 0.4
- Create a switch for Screen Wake Lock API, enable users to keep screen lit when cooking

feat: create a cooking mode

---

src/components/EditIngredientsList.tsx
src/components/EditInstructionsList.tsx
src/components/EditRecipeForm.tsx
src/components/SaveRecipeModal.tsx
src/components/TagsFilter.tsx

- Add options icon to input field, onclick displays trashcan for deleting ingredient/instruction
- Updated button for log in in save recipe modal
- Updated border radius for the dropdown in input search

feat: change trash icons to kebab icon in editrecipe

---

src/app/dashboard/[slug]/edit/page.tsx
src/app/dashboard/[slug]/page.tsx
src/app/dashboard/page.tsx
src/components/Breadcrumbs.tsx
src/components/EditIngredientsList.tsx
src/components/EditInstructionsList.tsx
src/components/EditRecipeForm.tsx
src/components/IngredientsAndInstructionsToggle.tsx
src/components/RecipeCard.tsx
src/components/RecipeForm.tsx
src/components/RecipesList.tsx
src/components/ScreenAwakeToggle.tsx

- Create breadcrumb navigation for dashboard / recipe / edit pages
- Move recipe info (author, time, servings) from `IngredientAndInstructionsToggle.tsx` to recipe page
- Add link to dashboard on `RecipesList.tsx`
- Update border radius on edit forms

feat: replace back arrow with breadcrumbs

---

src/components/RecipesList.tsx

- Update to include accidentally omitted function to display the correct recipes when filtering

fix: display the filtered recipes

---

next.env.d.ts
package-lock.json
package.json
src/components/Confetti.tsx
src/components/RecipeForm.tsx

Added food confetti when a recipe is successfully decluttered 🍔 🎉

feat: add js confetti

---

src/app/dashboard/[slug]/page.tsx

Original recipe opens in new tab when clicking the author link

feat: recipe opens in new tab

---

src/app/dashboard/page.tsx
src/app/index.css
src/app/layout.tsx
src/components/IngredientsAndInstructionsToggle.tsx
src/components/RandomRecipe.tsx

- Add functionality to the random recipe button
- Button opens modal with random recipe where you get the option to go to recipe or get a new random one
- Also tested changing background color to the cream one we have in navbar, this could be reversed or updated

feat: add a random recipe button for inspiration

---

src/components/Header/Navbar.tsx

- Display full name if less then 8 characters

feat: display a persons whole name in UserButton depending on if it fits or not

---

next.env.d.ts
src/components/IngredientsAndInstructionsToggle.tsx
src/components/RenderedInstructions.tsx

Added a custom index count for sectioned instructions, so that no instruction has the same index as another.

fix: fixed section instruction checkboxes

---

src/app/page.tsx
src/app/welcome/page.tsx
src/components/RecipeForm.tsx
src/components/WelcomeMessage.tsx

- Left align and add max-width to declutter form buttons

feat: make declutter and title left aligned

---

package-lock.json

```bash
joar@MBA: ~/github/recipe-declutter main
$ npm i                                                                                                 [13:49:00]
changed 1 package, and audited 575 packages in 961ms
171 packages are looking for funding
run `npm fund` for details
1 high severity vulnerability
To address all issues, run:
npm audit fix
Run `npm audit` for details.
joar@MBA: ~/github/recipe-declutter main
$ npm audit fix                                                                                         [13:49:05]
changed 1 package, and audited 575 packages in 873ms
171 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```

fix: update cross-spawn to version 7.0.6

---

src/components/SignUpForm.tsx

now opened on click on link "terms and conditions" instead of hover
https://github.com/user-attachments/assets/843c449c-308d-48c0-b808-125f7a2c39a8

make tooltip work on mobile

---

src/app/dashboard/[slug]/page.tsx
src/components/IngredientsAndInstructionsToggle.tsx

Added the same colored background on recipes as in desktop (white/grey depending on color scheme)

feat: added paper behind text on mobile size

---

src/components/ScreenAwakeToggle.tsx

changed to size md for accessibility

feat: increase size of screen awake component
